vich_uploader:
    db_driver: orm

    mappings:
        users_avatars:
            uri_prefix: /uploads/users/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/users/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true